### ISSUE TITLE
请问后端已经部署好了，前端需要怎么配置呢？

### ISSUE THREAD

**Issue by xianjianqiyuan** [GIS142857/X-Tok-backend#1]

**Comment by GIS142857** [comment]
首先你先 git clone https://github.com/GIS142857/douyin.git 这个仓库，然后你把 https://github.com/GIS142857/douyin-backend.git 这个仓库中 fronted 目录下的 src.zip 文件下载之后替换到前端项目中。最后修改一下前端项目中的/src/config/index.ts文件中的后端URL 地址，修改完之后根据前端项目的启动方式启动就可以了。

**Comment by xianjianqiyuan** [comment]
首先感谢回复，前后端都已经跑起来了，但是登录不进去，目前发现两个问题：
1、前端缺少js-cookie依赖
2、后端少上传了张表：db_douyin.tb_auth_access_tokens

**Comment by GIS142857** [comment]
npm install js-cookie

CREATE TABLE `tb_auth_access_tokens` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `uid` bigint DEFAULT '0',
  `client_id` int unsigned DEFAULT '1' COMMENT '普通用户的授权，默认为1',
  `token` varchar(600) DEFAULT NULL,
  `action_name` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT '' COMMENT 'login|update|reset表示token生成动作',
  `scopes` varchar(128) CHARACTER SET utf8mb3 COLLATE utf8mb3_unicode_ci DEFAULT '[*]' COMMENT '暂时预留,未启用',
  `revoked` tinyint(1) DEFAULT '0' COMMENT '是否撤销',
  `client_ip` varchar(128) DEFAULT NULL COMMENT 'ipv6最长为128位',
  `created_at` int DEFAULT NULL,
  `updated_at` int DEFAULT NULL,
  `expires_at` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `oauth_access_tokens_user_id_index` (`uid`)
) ENGINE=InnoDB AUTO_INCREMENT=178 DEFAULT CHARSET=utf8mb3

**Comment by GIS142857** [comment]
因为这个项目我最近一直在更新代码，可能有些文件疏忽了。

**Comment by dfrrk** [comment]
请问
按照上面所有步骤设置好了，并安装好js-cookie后，后台咋用呀？

我在用户登录页面http://localhost:3000/login/password 
输入19911220000/00000000的账号密码提示接口错误
[GIN] 2024/12/04 - 00:23:28 |[90;43m 400 [0m|       0s |       127.0.0.1 |[97;46m POST    [0m "/base/login"

**Comment by GIS142857** [comment]
> 请问 按照上面所有步骤设置好了，并安装好js-cookie后，后台咋用呀？
> 
> 我在用户登录页面http://localhost:3000/login/password 输入19911220000/00000000的账号密码提示接口错误 [GIN] 2024/12/04 - 00:23:28 |�[90;43m 400 �[0m| 0s | 127.0.0.1 |�[97;46m POST �[0m "/base/login"
应该是密码加密的问题，你看看 tb_accounts 里面的密码有没有加密。如果没有加密的话用 md5_encrypt.Base64Md5(password) 这个函数加密一下密码，更改到数据库中。然后应该就可以了。

**Comment by GIS142857** [comment]
> 请问 按照上面所有步骤设置好了，并安装好js-cookie后，后台咋用呀？
> 
> 我在用户登录页面http://localhost:3000/login/password 输入19911220000/00000000的账号密码提示接口错误 [GIN] 2024/12/04 - 00:23:28 |�[90;43m 400 �[0m| 0s | 127.0.0.1 |�[97;46m POST �[0m "/base/login"

觉得麻烦的话重新替换一下数据库，下载之后导入即可：
下载链接：https://117.50.163.130/videos/db_douyin.sql

**Comment by dfrrk** [comment]
感谢！请问我登录后台之后好像也发不了作品呀？
我该怎么添加新视频和修改其它的视频呢？

**Comment by GIS142857** [comment]
> 感谢！请问我登录后台之后好像也发不了作品呀？ 我该怎么添加新视频和修改其它的视频呢？

可以用 Python 代码导入视频，上传视频的功能开发好了，但是前端你需要把 fronted 文件夹中的 src 目录替换到你的前端项目中。另外还需要配置好 nginx 和后端的文件上传路径。

**Comment by GIS142857** [comment]
> 感谢！请问我登录后台之后好像也发不了作品呀？ 我该怎么添加新视频和修改其它的视频呢？

记得重新 pull 一下，src.zip 我刚刚更新了
